name: Metrics

on:
  #schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main", "master"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Sloan-Yang
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_achievements: yes
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_traffic: yes
